[package]
name = "stricter-bin"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
clap = "2"
failure = "0.1"
log = "0.4"
pretty_env_logger = "0.3"

[dependencies.stricter]
path = "../stricter"
